# Generated by Django 3.0.7 on 2020-08-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20200717_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
